---
version: '2'
services:
  logstash:
    build:
      context: build/logstash
      args:
        LOGSTASH_VERSION: "${LOGSTASH_VERSION}"
        LOGSTASH_DOWNLOAD_URL: "${LOGSTASH_DOWNLOAD_URL}"
    image: "${VERSIONED_IMAGE}"
