---
# A demonstration of running Logstash in Docker, with Elasticsearch, Kibana
# and various example Logstash input plugins.

version: '2'
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${VERSION_TAG}
    volumes:
      - ./examples/elastic-stack-demo/:/usr/share/logstash/pipeline/
    networks:
      - elastic-stack
    ports:
      # Beats input -- https://www.elastic.co/guide/en/logstash/5.0/plugins-inputs-beats.html
      - '5044:5044'

      # UDP input -- https://www.elastic.co/guide/en/logstash/master/plugins-inputs-udp.html#plugins-inputs-udp-codec
      - '43448:43448/udp'

      # Monitoring APIs -- https://www.elastic.co/guide/en/logstash/5.0/monitoring.html
      - '9600:9600'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION_TAG}
    networks:
      - elastic-stack

  kibana:
    image: docker.elastic.co/kibana/kibana:${VERSION_TAG}
    ports: [ '5601:5601' ]
    networks:
      - elastic-stack

  redis:
    image: redis
    ports: [ '6379:6379' ]
    networks:
      - elastic-stack

networks:
  elastic-stack:
